version: '3.8'

services:
  nginx-server:
    image: 'nginx:stable-alpine'
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # we are mounting the nginx configuration file, where the request will be redirected to the php-fpm container
    depends_on:
      - php-backend
      - my-sql

  php-backend:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php-backend
    volumes:
      - ./src:/var/www/html:delegated # delegating will improve the performance of the application
  my-sql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html:delegated

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: [ 'php', '/var/www/html/artisan' ]
  npm:
    image: 'node:14'
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
