version: "3.8"

services:
  mongodb:
    image: 'mongo'
    container_name: mongodb-server
    volumes:
      - mongodb-data:/data/db
    #environment: add environment variables here
    #env_file: add environment variables from a file
  backend:
    build: ./backend
    container_name: 'backend-server'
    ports:
      - '8080:8080'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/env
    depends_on:
      - mongodb

  frontend:
    container_name: 'frontend-server'
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodb-data:
  logs:
#networks: